name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  naisteamnotifier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512
        id: docker-build-push
        name: Build and push Docker image
        with:
          team: appsec
          image_suffix: naisteam
          pull: true
          build_args: |
            APP=naisteamnotifier
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/naisteamnotifier.yaml
          IMAGE: ${{ steps.docker-build-push.outputs.IMAGE }}
  secretsnotifier:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: nais/docker-build-push@31c3a7321909bcb20799fdf46153fec721fd9512
        id: docker-build-push
        name: Build and push Docker image
        with:
          team: appsec
          image_suffix: secrets
          pull: true
          build_args: |
            APP=secretsnotifier
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/secretsnotifier.yaml
          IMAGE: ${{ steps.docker-build-push.outputs.IMAGE }}